### ISSUE TITLE
Not compatible with ViaVersion

### ISSUE THREAD

**Issue by comfysquirrel** [boy0001/HoloPlots#2]
I get this error when trying to connect using a 1.9 client to a 1.8 server that has ViaVersion. The error only happens when HoloPlots is installed.
![screen shot 2016-03-06 at 9 22 58 am](https://cloud.githubusercontent.com/assets/6022168/13555079/07b0e65a-e37d-11e5-9383-39ce2f1e1966.png)

**Comment by boy0001** [comment]
HoloPlots uses holographic displays to create the holograms. All errors would need to be fixed on that end.
